### ISSUE TITLE
Liste des Pokémon

### ISSUE THREAD

**Issue by Lumios974** [Loic-Mathieu/Shiny-tracker-obs#1]
Depuis 

>Add > Pokemon

Si on charge la liste jusqu'aux formes (Régionales, spécifiques au Pokémon), la liste crash car elle à l'air de charger des données inexistantes.

**Comment by Loic-Mathieu** [comment]
Fixed in next version.

This list was loaded in a way that we fetched Pokémon by batch of 100. After each new load, batches were concatenated in the subscribe of the request observable, which was cached (as the complete list of Pokémon).
The issue was divided in two parts of this method: 
1. By concatenating lists in the observable it resets the end result after each request, which is why the list was so unstable.  
2. The filter was trying to fetch data from non existing Pokémon around the end, which caused the crash.

Solution:
I refactored how the request were send to the Poké API to avoid facing this king of issue again. Now instead of caching one list of Pokémon and updating it, the app will cache each batch of 100 Pokémon and the concat will be performed only when the data is loaded in the list. This will also avoid to load a whole list of data in request.
